// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<string>;

export function HasConfig():Promise<boolean>;

export function HideWindow():Promise<void>;

export function PickFolder():Promise<string>;

export function QuitApp():Promise<void>;

export function SaveConfigAndStart(arg1:main.Config):Promise<string>;

export function ShowWindow():Promise<void>;

export function StopMonitor():Promise<void>;
