// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfigAndStart(arg1) {
  return window['go']['main']['App']['SaveConfigAndStart'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}
